# Generated by Django 5.1.5 on 2025-01-21 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_avatar_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=30, verbose_name='specialization')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='experience')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='location')),
                ('clinic_name', models.CharField(blank=True, max_length=30, verbose_name='clinic name')),
                ('cunsultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cunsultation fee')),
                ('is_consultation_fee', models.BooleanField(default=False, verbose_name='consultation fee')),
                ('avaible_today', models.BooleanField(default=False, verbose_name='avaible today')),
                ('rating_percentage', models.PositiveIntegerField(default=0, verbose_name='rating percentage')),
                ('patient_stories', models.PositiveIntegerField(default=0, verbose_name='patient stories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='title')),
                ('img', models.ImageField(upload_to='', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'news',
            },
        ),
    ]
