# Generated by Django 5.1.5 on 2025-01-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctor_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
